sudo: false
language: node_js
node_js:
  - 6
  - 9

cache:
  yarn: true
  directories:
    - node_modules

env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9

script:
  - yarn
  - yarn build
  - yarn test
