sudo: false
language: node_js
node_js:
  - 6
  - 9

cache:
  yarn: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - yarn
  - yarn build
  - yarn test
